# Generated by Django 3.1.5 on 2021-01-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'o2 사용자'},
        ),
    ]
